version: "3.9"
services:
  smartweather-dev:
    container_name: smartweather-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_WEATHER_API_KEY=7e2b87ceb8bae9f172e4a1f1cc9d01bb
    stdin_open: true
    tty: true