services:
  smartweather-dev:
    container_name: smartweather-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
